on:
  release:
    types: [created]

permissions:
  packages: write
  contents: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goversion: 1.21.6
          sha256sum: true
          goarch: amd64
